# AI Conversation App Configuration
# Based on Conversify architecture with 3D character integration

app:
  name: "AI Conversation App"
  version: "0.1.0"
  window:
    width: 1200
    height: 800
    resizable: true
    fullscreen: false
    always_on_top: false

# Audio Configuration
audio:
  input:
    device: "default"
    sample_rate: 16000
    channels: 1
    buffer_size: 1024
    noise_suppression: true
    echo_cancellation: true
  
  output:
    device: "default"
    sample_rate: 24000
    channels: 1
    volume: 0.8
    low_latency: true

# Speech-to-Text Configuration
stt:
  provider: "whisper"
  model: "whisper-small"
  language: "auto"
  real_time: true
  vad_enabled: true
  silence_threshold: 0.01
  min_speech_duration: 0.3
  max_speech_duration: 30.0

# Text-to-Speech Configuration
tts:
  provider: "local"
  voice: "neural"
  speed: 1.0
  pitch: 1.0
  volume: 0.8
  streaming: true
  low_latency: true
  generate_visemes: true

# Large Language Model Configuration
llm:
  provider: "local"
  model: "llama-3.2-3b-instruct"
  max_tokens: 2048
  temperature: 0.7
  top_p: 0.9
  stream: true
  context_window: 8192
  system_prompt: |
    You are a helpful AI assistant engaged in a natural conversation.
    Keep responses concise and conversational. Show personality and emotion
    appropriate to the context. You can see and hear the user.

# Vision Configuration
vision:
  enabled: true
  model: "clip-vit-base"
  input_resolution: [224, 224]
  fps: 10
  object_detection: true
  face_detection: true
  emotion_recognition: true

# 3D Character Configuration
character:
  enabled: true
  provider: "readyplayerme"
  avatar_url: ""
  animations:
    idle: "idle.fbx"
    talking: "talking.fbx"
    listening: "listening.fbx"
    thinking: "thinking.fbx"
  
  lip_sync:
    enabled: true
    viseme_mapping: "arkit"
    smoothing: 0.3
    intensity: 1.0
    real_time: true
  
  facial_expressions:
    enabled: true
    emotion_mapping: true
    blink_rate: 3.0
    eye_tracking: false
  
  rendering:
    quality: "high"
    shadows: true
    lighting: "dynamic"
    anti_aliasing: true
    fps_target: 60

# Performance Configuration
performance:
  hardware_acceleration: true
  gpu_rendering: true
  multi_threading: true
  memory_optimization: true
  low_latency_mode: true
  target_fps: 60
  audio_buffer_size: 512
  video_buffer_size: 3

# Memory and Conversation Configuration
memory:
  enabled: true
  max_history: 50
  context_retention: 10
  save_conversations: true
  conversation_timeout: 1800  # 30 minutes

# Logging Configuration
logging:
  level: "info"
  file_logging: true
  console_logging: true
  log_file: "logs/app.log"
  max_file_size: "10MB"
  max_files: 5

# Development Configuration
development:
  debug_mode: false
  hot_reload: true
  performance_monitoring: true
  error_reporting: true
  telemetry: false