app:
  name: "AI Conversation App"
  version: "0.1.0"
  window:
    width: 1200
    height: 800
    resizable: true
    fullscreen: false
    always_on_top: false

audio:
  input:
    device: "default"
    sample_rate: 16000
    channels: 1
    buffer_size: 1024
    noise_suppression: true
    echo_cancellation: true
  output:
    device: "default"
    sample_rate: 44100
    channels: 2
    volume: 1.0
    low_latency: true

stt:
  provider: "whisper"
  model: "base"
  language: "en"
  real_time: true
  vad_enabled: true
  silence_threshold: 0.01
  min_speech_duration: 0.5
  max_speech_duration: 30.0

tts:
  provider: "system"
  voice: "default"
  speed: 1.0
  pitch: 1.0
  volume: 1.0
  streaming: true
  low_latency: true
  generate_visemes: true

llm:
  provider: "openai"
  model: "gpt-4"
  max_tokens: 2048
  temperature: 0.7
  top_p: 1.0
  stream: true
  context_window: 8192
  system_prompt: "You are a helpful AI assistant."

vision:
  enabled: false
  model: "yolo"
  input_resolution: [640, 480]
  fps: 30
  object_detection: true
  face_detection: true
  emotion_recognition: true

character:
  enabled: true
  provider: "readyplayerme"
  avatar_url: "https://models.readyplayer.me/64bfa15f0e72c63d7c3934a6.glb"
  animations:
    idle: "idle"
    talking: "talking"
    listening: "listening"
    thinking: "thinking"
  lip_sync:
    enabled: true
    viseme_mapping: "arkit"
    smoothing: 0.5
    intensity: 1.0
    real_time: true
  facial_expressions:
    enabled: true
    emotion_mapping: true
    blink_rate: 0.1
    eye_tracking: false
  rendering:
    quality: "high"
    shadows: true
    lighting: "studio"
    anti_aliasing: true
    fps_target: 60

performance:
  hardware_acceleration: true
  gpu_rendering: true
  multi_threading: true
  memory_optimization: true
  low_latency_mode: true
  target_fps: 60
  audio_buffer_size: 512
  video_buffer_size: 1024

memory:
  enabled: true
  max_history: 100
  context_retention: 10
  save_conversations: true
  conversation_timeout: 3600

logging:
  level: "info"
  file_logging: true
  console_logging: true
  log_file: "app.log"
  max_file_size: "10MB"
  max_files: 5

development:
  debug_mode: true
  hot_reload: true
  performance_monitoring: true
  error_reporting: true
  telemetry: false